### PR TITLE
Fix iOS launch images

### PR DESCRIPTION
**Pull request by samaxes**
This time all the changes have been tested with assets catalogs.
I apologise for the previous PR.

### CODE REVIEW

**Comment by BrunoCartier** [comment]
Your PR seemed great, why did you close it?

**Comment by samaxes** [comment]
Hi @BrunoCartier, I just wanted to confirm why there was no slot for iPad Pro launch images.
Seems that iPad Pro does not support launch images anymore: https://openradar.appspot.com/22915712.

**Comment by samaxes** [comment]
I just resolved the code conflicts after the last @AlexDisler changes.
Can you give me any feedback on when do you plan on merging this PR?

**Comment by BrunoCartier** [comment]
Thanks for the cleanup :+1:

**Pull request merged**
