### PR TITLE
Added params for splash and config

### PR DESCRIPTION
**Pull request by RamonGebben**
Added yargs to support cli arguments.

### CODE REVIEW

**Comment by zpeterg** [comment]
Please accept the changes and add to npm.

**Comment by RamonGebben** [comment]
@zpeterg since this PR never got accepted, I deployed a version with these features on npm under the name `cordova-splash-cli` use that if you need it.

**Comment by zpeterg** [comment]
Great, thanks!

**Comment by BrunoCartier** [comment]
Hey,

You can now specify CLI args with the latest version (0.0.9).

Thanks a lot for your pull request :+1:

**Comment by zpeterg** [comment]
Thanks!

**Pull request closed without merging**
